/* 
 * Copyright (C) 2017 Me
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package view;

import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author Eling Supriyatno
 */
public class MenuUtamaView extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtamaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuPenyerahanLaundry = new javax.swing.JMenuItem();
        menuPengambilanLaundry = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem3.setText("Update Password");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master");

        jMenuItem4.setText("Aset");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Transaksi");

        menuPenyerahanLaundry.setText("Penyerahan Laundry");
        menuPenyerahanLaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenyerahanLaundryActionPerformed(evt);
            }
        });
        jMenu4.add(menuPenyerahanLaundry);

        menuPengambilanLaundry.setText("Pengambilan Laundry");
        menuPengambilanLaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPengambilanLaundryActionPerformed(evt);
            }
        });
        jMenu4.add(menuPengambilanLaundry);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Laporan");
        jMenuBar1.add(jMenu5);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPenyerahanLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenyerahanLaundryActionPerformed
        // TODO add your handling code here:
        PenyerahanLaundryView penyerahanLaundryView = new PenyerahanLaundryView();
        jDesktopPane1.add(penyerahanLaundryView);
        Dimension screen = this.getSize();
        Dimension frame = penyerahanLaundryView.getSize();
        //penyerahanLaundryView.setLocation ((screen.width - frame.width) / 2, (screen.height - frame.height) / 2);
        penyerahanLaundryView.setVisible(true);
        //penyerahanLaundryView.show();
    }//GEN-LAST:event_menuPenyerahanLaundryActionPerformed

    private void menuPengambilanLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPengambilanLaundryActionPerformed
        // TODO add your handling code here:
        PengambilanLaundryView pengambilanLaundryView = new PengambilanLaundryView();
        jDesktopPane1.add(pengambilanLaundryView);
        pengambilanLaundryView.setVisible(true);
    }//GEN-LAST:event_menuPengambilanLaundryActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem menuPengambilanLaundry;
    private javax.swing.JMenuItem menuPenyerahanLaundry;
    // End of variables declaration//GEN-END:variables
}
