/* 
 * Copyright (C) 2017 Me
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package view;

import controller.NikiLaundryController;

/**
 *
 * @author Eling Supriyatno
 */
public class NikiLaundryView extends javax.swing.JFrame {

  private final NikiLaundryController controller;

  /**
   * Creates new form NikiLaundryView
   */
  public NikiLaundryView() {
    initComponents();
    controller = new NikiLaundryController();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      bg = new javax.swing.JPanel();
      panelLogin = new javax.swing.JPanel();
      txtNikiLaundryLogin = new javax.swing.JLabel();
      sparatorNikiLaundryLogin = new javax.swing.JSeparator();
      iconUserName = new javax.swing.JLabel();
      txtUserName = new javax.swing.JTextField();
      sparatorUserName = new javax.swing.JSeparator();
      iconPassword = new javax.swing.JLabel();
      txtPassword = new javax.swing.JPasswordField();
      sparatuorPassword = new javax.swing.JSeparator();
      btnLogin = new javax.swing.JButton();
      panelMenu = new javax.swing.JPanel();
      txtNikiLaundryMenu = new javax.swing.JLabel();
      sparatorNikiLaundryMenu = new javax.swing.JSeparator();
      btnLaundry = new javax.swing.JPanel();
      iconBtnLaundry = new javax.swing.JLabel();
      txtbtnLaundry = new javax.swing.JLabel();
      btnMaster = new javax.swing.JPanel();
      iconBtnMaster = new javax.swing.JLabel();
      txtBtnMaster = new javax.swing.JLabel();
      btnAset = new javax.swing.JPanel();
      iconBtnAset = new javax.swing.JLabel();
      txtBtnAset = new javax.swing.JLabel();
      btnLaporan = new javax.swing.JPanel();
      iconBtnLaporan = new javax.swing.JLabel();
      txtBtnLaporan = new javax.swing.JLabel();
      baseContainer = new javax.swing.JDesktopPane();
      btnExit = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setLocationByPlatform(true);
      setUndecorated(true);
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowClosing(java.awt.event.WindowEvent evt) {
            formWindowClosing(evt);
         }
         public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened(evt);
         }
      });

      bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      panelLogin.setBackground(new java.awt.Color(54, 33, 89));
      panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      txtNikiLaundryLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
      txtNikiLaundryLogin.setForeground(new java.awt.Color(255, 0, 255));
      txtNikiLaundryLogin.setText("Niki Laundry");
      panelLogin.add(txtNikiLaundryLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, -1));

      sparatorNikiLaundryLogin.setBackground(new java.awt.Color(255, 0, 255));
      sparatorNikiLaundryLogin.setForeground(new java.awt.Color(255, 0, 255));
      sparatorNikiLaundryLogin.setPreferredSize(new java.awt.Dimension(50, 5));
      panelLogin.add(sparatorNikiLaundryLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 20));

      iconUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
      panelLogin.add(iconUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

      txtUserName.setBackground(new java.awt.Color(54, 33, 89));
      txtUserName.setForeground(new java.awt.Color(255, 0, 255));
      txtUserName.setToolTipText("enter user name");
      txtUserName.setBorder(null);
      txtUserName.setCaretColor(new java.awt.Color(255, 255, 255));
      txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            txtUserNameFocusGained(evt);
         }
      });
      txtUserName.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtUserNameActionPerformed(evt);
         }
      });
      panelLogin.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 170, -1));

      sparatorUserName.setBackground(new java.awt.Color(255, 0, 255));
      sparatorUserName.setForeground(new java.awt.Color(255, 0, 255));
      panelLogin.add(sparatorUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 170, 20));

      iconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/password.png"))); // NOI18N
      panelLogin.add(iconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

      txtPassword.setBackground(new java.awt.Color(54, 33, 89));
      txtPassword.setForeground(new java.awt.Color(255, 0, 255));
      txtPassword.setToolTipText("enter password");
      txtPassword.setBorder(null);
      txtPassword.setCaretColor(new java.awt.Color(255, 255, 255));
      txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            txtPasswordFocusGained(evt);
         }
      });
      txtPassword.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtPasswordActionPerformed(evt);
         }
      });
      panelLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 170, -1));

      sparatuorPassword.setBackground(new java.awt.Color(255, 0, 255));
      sparatuorPassword.setForeground(new java.awt.Color(255, 0, 255));
      panelLogin.add(sparatuorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 170, 20));

      btnLogin.setBackground(new java.awt.Color(255, 0, 255));
      btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      btnLogin.setForeground(new java.awt.Color(54, 33, 89));
      btnLogin.setText("Login");
      btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 255), 1, true));
      btnLogin.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLoginActionPerformed(evt);
         }
      });
      panelLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 80, 30));

      bg.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 600));

      panelMenu.setBackground(new java.awt.Color(54, 33, 89));
      panelMenu.setEnabled(false);
      panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      txtNikiLaundryMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
      txtNikiLaundryMenu.setForeground(new java.awt.Color(255, 0, 255));
      txtNikiLaundryMenu.setText("Niki Laundry");
      panelMenu.add(txtNikiLaundryMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, -1));

      sparatorNikiLaundryMenu.setBackground(new java.awt.Color(255, 0, 255));
      sparatorNikiLaundryMenu.setForeground(new java.awt.Color(255, 0, 255));
      sparatorNikiLaundryMenu.setPreferredSize(new java.awt.Dimension(50, 5));
      panelMenu.add(sparatorNikiLaundryMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 20));

      btnLaundry.setBackground(new java.awt.Color(85, 65, 118));
      btnLaundry.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            btnLaundryMousePressed(evt);
         }
      });

      iconBtnLaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/washing_machine.png"))); // NOI18N

      txtbtnLaundry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      txtbtnLaundry.setForeground(new java.awt.Color(255, 0, 255));
      txtbtnLaundry.setText("Laundry");

      javax.swing.GroupLayout btnLaundryLayout = new javax.swing.GroupLayout(btnLaundry);
      btnLaundry.setLayout(btnLaundryLayout);
      btnLaundryLayout.setHorizontalGroup(
         btnLaundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(btnLaundryLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(iconBtnLaundry)
            .addGap(18, 18, 18)
            .addComponent(txtbtnLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(54, Short.MAX_VALUE))
      );
      btnLaundryLayout.setVerticalGroup(
         btnLaundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(btnLaundryLayout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(btnLaundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(txtbtnLaundry)
               .addComponent(iconBtnLaundry))
            .addGap(12, 12, 12))
      );

      panelMenu.add(btnLaundry, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 270, 50));

      btnMaster.setBackground(new java.awt.Color(54, 33, 89));
      btnMaster.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            btnMasterMousePressed(evt);
         }
      });

      iconBtnMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/master.png"))); // NOI18N

      txtBtnMaster.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      txtBtnMaster.setForeground(new java.awt.Color(255, 0, 255));
      txtBtnMaster.setText("Master");

      javax.swing.GroupLayout btnMasterLayout = new javax.swing.GroupLayout(btnMaster);
      btnMaster.setLayout(btnMasterLayout);
      btnMasterLayout.setHorizontalGroup(
         btnMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(btnMasterLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(iconBtnMaster)
            .addGap(18, 18, 18)
            .addComponent(txtBtnMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(55, Short.MAX_VALUE))
      );
      btnMasterLayout.setVerticalGroup(
         btnMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(btnMasterLayout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(btnMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(txtBtnMaster)
               .addComponent(iconBtnMaster))
            .addGap(12, 12, 12))
      );

      panelMenu.add(btnMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

      btnAset.setBackground(new java.awt.Color(54, 33, 89));
      btnAset.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            btnAsetMousePressed(evt);
         }
      });

      iconBtnAset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/aset.png"))); // NOI18N

      txtBtnAset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      txtBtnAset.setForeground(new java.awt.Color(255, 0, 255));
      txtBtnAset.setText("Aset");

      javax.swing.GroupLayout btnAsetLayout = new javax.swing.GroupLayout(btnAset);
      btnAset.setLayout(btnAsetLayout);
      btnAsetLayout.setHorizontalGroup(
         btnAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(btnAsetLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(iconBtnAset)
            .addGap(18, 18, 18)
            .addComponent(txtBtnAset, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(55, Short.MAX_VALUE))
      );
      btnAsetLayout.setVerticalGroup(
         btnAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(btnAsetLayout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(btnAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(txtBtnAset)
               .addComponent(iconBtnAset))
            .addGap(12, 12, 12))
      );

      panelMenu.add(btnAset, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

      btnLaporan.setBackground(new java.awt.Color(54, 33, 89));
      btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            btnLaporanMousePressed(evt);
         }
      });

      iconBtnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/report.png"))); // NOI18N

      txtBtnLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      txtBtnLaporan.setForeground(new java.awt.Color(255, 0, 255));
      txtBtnLaporan.setText("Laporan");

      javax.swing.GroupLayout btnLaporanLayout = new javax.swing.GroupLayout(btnLaporan);
      btnLaporan.setLayout(btnLaporanLayout);
      btnLaporanLayout.setHorizontalGroup(
         btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(btnLaporanLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(iconBtnLaporan)
            .addGap(18, 18, 18)
            .addComponent(txtBtnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(55, Short.MAX_VALUE))
      );
      btnLaporanLayout.setVerticalGroup(
         btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(btnLaporanLayout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(txtBtnLaporan)
               .addComponent(iconBtnLaporan))
            .addGap(12, 12, 12))
      );

      panelMenu.add(btnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

      bg.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 600));

      baseContainer.setBackground(new java.awt.Color(255, 51, 255));

      javax.swing.GroupLayout baseContainerLayout = new javax.swing.GroupLayout(baseContainer);
      baseContainer.setLayout(baseContainerLayout);
      baseContainerLayout.setHorizontalGroup(
         baseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 730, Short.MAX_VALUE)
      );
      baseContainerLayout.setVerticalGroup(
         baseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 560, Short.MAX_VALUE)
      );

      bg.add(baseContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 730, 560));

      btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
      btnExit.setForeground(new java.awt.Color(54, 33, 89));
      btnExit.setText("X");
      btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            btnExitMousePressed(evt);
         }
      });
      bg.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, 20));

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
      controller.tutupAplikasi(this);
    }//GEN-LAST:event_btnExitMousePressed

    private void btnLaundryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaundryMousePressed
      controller.menuLaundryPressed(this);
    }//GEN-LAST:event_btnLaundryMousePressed

    private void btnMasterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterMousePressed
      controller.menuMasterPressed(this);
    }//GEN-LAST:event_btnMasterMousePressed

    private void btnAsetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsetMousePressed
      controller.menuAsetPressed(this);
    }//GEN-LAST:event_btnAsetMousePressed

    private void btnLaporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMousePressed
      controller.menuLaporanPressed(this);
    }//GEN-LAST:event_btnLaporanMousePressed

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
      txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
      controller.loginButtonActionPerform();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusGained
      txtUserName.setText("");
    }//GEN-LAST:event_txtUserNameFocusGained

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
      txtPassword.requestFocus();
    }//GEN-LAST:event_txtUserNameActionPerformed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    controller.tutupAplikasi(this);
  }//GEN-LAST:event_formWindowClosing

  private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    panelLogin.setVisible(false);
    panelMenu.setVisible(true);
  }//GEN-LAST:event_btnLoginActionPerformed

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    controller.umpetnaPanelPasPertamaJalan(this);
  }//GEN-LAST:event_formWindowOpened

   // Variables declaration - do not modify//GEN-BEGIN:variables
   public static javax.swing.JDesktopPane baseContainer;
   private javax.swing.JPanel bg;
   public static javax.swing.JPanel btnAset;
   private javax.swing.JLabel btnExit;
   public static javax.swing.JPanel btnLaporan;
   public static javax.swing.JPanel btnLaundry;
   private javax.swing.JButton btnLogin;
   public static javax.swing.JPanel btnMaster;
   private javax.swing.JLabel iconBtnAset;
   private javax.swing.JLabel iconBtnLaporan;
   private javax.swing.JLabel iconBtnLaundry;
   private javax.swing.JLabel iconBtnMaster;
   private javax.swing.JLabel iconPassword;
   private javax.swing.JLabel iconUserName;
   public static javax.swing.JPanel panelLogin;
   public static javax.swing.JPanel panelMenu;
   private javax.swing.JSeparator sparatorNikiLaundryLogin;
   private javax.swing.JSeparator sparatorNikiLaundryMenu;
   private javax.swing.JSeparator sparatorUserName;
   private javax.swing.JSeparator sparatuorPassword;
   private javax.swing.JLabel txtBtnAset;
   private javax.swing.JLabel txtBtnLaporan;
   private javax.swing.JLabel txtBtnMaster;
   private javax.swing.JLabel txtNikiLaundryLogin;
   private javax.swing.JLabel txtNikiLaundryMenu;
   public static javax.swing.JPasswordField txtPassword;
   public static javax.swing.JTextField txtUserName;
   private javax.swing.JLabel txtbtnLaundry;
   // End of variables declaration//GEN-END:variables
}
