/*
 * Copyright (C) 2017 triastowo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package view.internal;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author triastowo
 */
public class LaporanInternalFrame extends javax.swing.JInternalFrame {

  /**
   * Creates new form LaporanInternalFrame
   */
  public LaporanInternalFrame() {
    ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelMenuLaporan = new javax.swing.JPanel();
    ribon4 = new javax.swing.JPanel();
    jScrollPane4 = new javax.swing.JScrollPane();
    tabelData3 = new javax.swing.JTable();

    ribon4.setBackground(new java.awt.Color(142, 53, 239));

    javax.swing.GroupLayout ribon4Layout = new javax.swing.GroupLayout(ribon4);
    ribon4.setLayout(ribon4Layout);
    ribon4Layout.setHorizontalGroup(
      ribon4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    ribon4Layout.setVerticalGroup(
      ribon4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 160, Short.MAX_VALUE)
    );

    tabelData3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    tabelData3.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane4.setViewportView(tabelData3);

    javax.swing.GroupLayout panelMenuLaporanLayout = new javax.swing.GroupLayout(panelMenuLaporan);
    panelMenuLaporan.setLayout(panelMenuLaporanLayout);
    panelMenuLaporanLayout.setHorizontalGroup(
      panelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelMenuLaporanLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
          .addComponent(ribon4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    panelMenuLaporanLayout.setVerticalGroup(
      panelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelMenuLaporanLayout.createSequentialGroup()
        .addComponent(ribon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        .addContainerGap())
    );

    getContentPane().add(panelMenuLaporan, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane4;
  public static javax.swing.JPanel panelMenuLaporan;
  private javax.swing.JPanel ribon4;
  private javax.swing.JTable tabelData3;
  // End of variables declaration//GEN-END:variables
}
