/*
 * Copyright (C) 2017 triastowo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package view.internal;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author triastowo
 */
public class LaundryInternalFrame extends javax.swing.JInternalFrame {

  /**
   * Creates new form LaundryInternalFrame
   */
  public LaundryInternalFrame() {
    ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    menuLaundry = new javax.swing.JTabbedPane();
    tabPenyerahan = new javax.swing.JPanel();
    txtNamaPenyerahan = new javax.swing.JTextField();
    txtNoNotaPenyerahan = new javax.swing.JTextField();
    txtTglTerimaPenyerahan = new javax.swing.JTextField();
    txtTglJadiPenyerahan = new javax.swing.JTextField();
    txtJumlahPenyerahan = new javax.swing.JTextField();
    txtBanyakCuciPenyerahan = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tabelPenyerahan = new javax.swing.JTable();
    cbPewangiPenyerahan = new javax.swing.JComboBox<>();
    cbLayananPenyerahan = new javax.swing.JComboBox<>();
    tabPengambilan = new javax.swing.JPanel();
    txtNamaPengambilan = new javax.swing.JTextField();
    txtNoNotaPengambilan = new javax.swing.JTextField();
    txtTglTerimaPengambilan = new javax.swing.JTextField();
    txtTglJadiPengambilan = new javax.swing.JTextField();
    txtJumlahPengambilan = new javax.swing.JTextField();
    txtBanyaknyaCuciPengambilan = new javax.swing.JLabel();
    jScrollPane6 = new javax.swing.JScrollPane();
    tabelPengambilan = new javax.swing.JTable();
    cbPewangiPengambilan = new javax.swing.JComboBox<>();
    cdLayananPengambilan = new javax.swing.JComboBox<>();

    setBorder(null);

    menuLaundry.setBackground(new java.awt.Color(142, 53, 239));
    menuLaundry.setPreferredSize(new java.awt.Dimension(730, 130));

    tabPenyerahan.setBackground(new java.awt.Color(142, 53, 239));
    tabPenyerahan.setPreferredSize(new java.awt.Dimension(730, 130));

    txtNamaPenyerahan.setText("Nama");
    txtNamaPenyerahan.setToolTipText("");
    txtNamaPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNamaPenyerahanActionPerformed(evt);
      }
    });

    txtNoNotaPenyerahan.setText("No. Nota");
    txtNoNotaPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNoNotaPenyerahanActionPerformed(evt);
      }
    });

    txtTglTerimaPenyerahan.setText("Tgl. Terima");
    txtTglTerimaPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtTglTerimaPenyerahanActionPerformed(evt);
      }
    });

    txtTglJadiPenyerahan.setText("Tgl. Jadi");
    txtTglJadiPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtTglJadiPenyerahanActionPerformed(evt);
      }
    });

    txtJumlahPenyerahan.setText("Jumlah (Kg)");
    txtJumlahPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtJumlahPenyerahanActionPerformed(evt);
      }
    });

    txtBanyakCuciPenyerahan.setText("anda sudah [...] kali cuci");

    tabelPenyerahan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    tabelPenyerahan.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(tabelPenyerahan);

    cbPewangiPenyerahan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    cbLayananPenyerahan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout tabPenyerahanLayout = new javax.swing.GroupLayout(tabPenyerahan);
    tabPenyerahan.setLayout(tabPenyerahanLayout);
    tabPenyerahanLayout.setHorizontalGroup(
      tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(tabPenyerahanLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(tabPenyerahanLayout.createSequentialGroup()
            .addComponent(txtNamaPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(133, 133, 133)
            .addComponent(txtTglTerimaPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(tabPenyerahanLayout.createSequentialGroup()
            .addComponent(txtNoNotaPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(133, 133, 133)
            .addComponent(txtTglJadiPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(tabPenyerahanLayout.createSequentialGroup()
            .addGroup(tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(cbPewangiPenyerahan, 0, 183, Short.MAX_VALUE)
              .addComponent(cbLayananPenyerahan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(133, 133, 133)
            .addGroup(tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(txtJumlahPenyerahan)
              .addComponent(txtBanyakCuciPenyerahan, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))))
        .addContainerGap(223, Short.MAX_VALUE))
      .addComponent(jScrollPane1)
    );
    tabPenyerahanLayout.setVerticalGroup(
      tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(tabPenyerahanLayout.createSequentialGroup()
        .addGap(6, 6, 6)
        .addGroup(tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtTglTerimaPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtNamaPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(6, 6, 6)
        .addGroup(tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtTglJadiPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtNoNotaPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cbPewangiPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtJumlahPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtBanyakCuciPenyerahan)
          .addComponent(cbLayananPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
    );

    menuLaundry.addTab("Penyerahan", tabPenyerahan);

    tabPengambilan.setBackground(new java.awt.Color(142, 53, 239));

    txtNamaPengambilan.setText("Nama");
    txtNamaPengambilan.setToolTipText("");
    txtNamaPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNamaPengambilanActionPerformed(evt);
      }
    });

    txtNoNotaPengambilan.setText("No. Nota");
    txtNoNotaPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNoNotaPengambilanActionPerformed(evt);
      }
    });

    txtTglTerimaPengambilan.setText("Tgl. Terima");
    txtTglTerimaPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtTglTerimaPengambilanActionPerformed(evt);
      }
    });

    txtTglJadiPengambilan.setText("Tgl. Jadi");
    txtTglJadiPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtTglJadiPengambilanActionPerformed(evt);
      }
    });

    txtJumlahPengambilan.setText("Jumlah (Kg)");
    txtJumlahPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtJumlahPengambilanActionPerformed(evt);
      }
    });

    txtBanyaknyaCuciPengambilan.setText("anda sudah [...] kali cuci");

    tabelPengambilan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    tabelPengambilan.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane6.setViewportView(tabelPengambilan);

    cbPewangiPengambilan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    cdLayananPengambilan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout tabPengambilanLayout = new javax.swing.GroupLayout(tabPengambilan);
    tabPengambilan.setLayout(tabPengambilanLayout);
    tabPengambilanLayout.setHorizontalGroup(
      tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(tabPengambilanLayout.createSequentialGroup()
        .addGroup(tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(tabPengambilanLayout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(txtNamaPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(133, 133, 133)
            .addComponent(txtTglTerimaPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(tabPengambilanLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(txtNoNotaPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(133, 133, 133)
            .addComponent(txtTglJadiPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(tabPengambilanLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(cdLayananPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(cbPewangiPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(133, 133, 133)
            .addGroup(tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(txtJumlahPengambilan)
              .addComponent(txtBanyaknyaCuciPengambilan, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))))
        .addContainerGap(223, Short.MAX_VALUE))
      .addComponent(jScrollPane6)
    );
    tabPengambilanLayout.setVerticalGroup(
      tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(tabPengambilanLayout.createSequentialGroup()
        .addGap(6, 6, 6)
        .addGroup(tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtNamaPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtTglTerimaPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(6, 6, 6)
        .addGroup(tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtTglJadiPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtNoNotaPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(tabPengambilanLayout.createSequentialGroup()
            .addComponent(txtJumlahPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtBanyaknyaCuciPengambilan))
          .addGroup(tabPengambilanLayout.createSequentialGroup()
            .addComponent(cbPewangiPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cdLayananPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
    );

    menuLaundry.addTab("Pengambilan", tabPengambilan);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(menuLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(menuLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtNamaPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPenyerahanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtNamaPenyerahanActionPerformed

  private void txtNoNotaPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoNotaPenyerahanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtNoNotaPenyerahanActionPerformed

  private void txtTglTerimaPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglTerimaPenyerahanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtTglTerimaPenyerahanActionPerformed

  private void txtTglJadiPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglJadiPenyerahanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtTglJadiPenyerahanActionPerformed

  private void txtJumlahPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahPenyerahanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtJumlahPenyerahanActionPerformed

  private void txtNamaPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtNamaPengambilanActionPerformed

  private void txtNoNotaPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoNotaPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtNoNotaPengambilanActionPerformed

  private void txtTglTerimaPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglTerimaPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtTglTerimaPengambilanActionPerformed

  private void txtTglJadiPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglJadiPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtTglJadiPengambilanActionPerformed

  private void txtJumlahPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtJumlahPengambilanActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox<String> cbLayananPenyerahan;
  private javax.swing.JComboBox<String> cbPewangiPengambilan;
  private javax.swing.JComboBox<String> cbPewangiPenyerahan;
  private javax.swing.JComboBox<String> cdLayananPengambilan;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane6;
  private javax.swing.JTabbedPane menuLaundry;
  private javax.swing.JPanel tabPengambilan;
  private javax.swing.JPanel tabPenyerahan;
  private javax.swing.JTable tabelPengambilan;
  private javax.swing.JTable tabelPenyerahan;
  private javax.swing.JLabel txtBanyakCuciPenyerahan;
  private javax.swing.JLabel txtBanyaknyaCuciPengambilan;
  private javax.swing.JTextField txtJumlahPengambilan;
  private javax.swing.JTextField txtJumlahPenyerahan;
  private javax.swing.JTextField txtNamaPengambilan;
  private javax.swing.JTextField txtNamaPenyerahan;
  private javax.swing.JTextField txtNoNotaPengambilan;
  private javax.swing.JTextField txtNoNotaPenyerahan;
  private javax.swing.JTextField txtTglJadiPengambilan;
  private javax.swing.JTextField txtTglJadiPenyerahan;
  private javax.swing.JTextField txtTglTerimaPengambilan;
  private javax.swing.JTextField txtTglTerimaPenyerahan;
  // End of variables declaration//GEN-END:variables
}
