/*
 * Copyright (C) 2017 triastowo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package view.internal;

import controller.LaundryController;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.jdesktop.swingx.JXDatePicker;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author triastowo
 */
public class LaundryInternalFrame extends javax.swing.JInternalFrame {

  private final LaundryController controller;

  /**
   * Creates new form LaundryInternalFrame
   */
  public LaundryInternalFrame() {
    controller = new LaundryController();

    ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    menuLaundry = new javax.swing.JTabbedPane();
    tabPenyerahan = new javax.swing.JPanel();
    txtNamaPenyerahan = new javax.swing.JTextField();
    txtNoNotaPenyerahan = new javax.swing.JTextField();
    txtJumlahPenyerahan = new javax.swing.JTextField();
    cbPewangiPenyerahan = new javax.swing.JComboBox<>();
    cbLayananPenyerahan = new javax.swing.JComboBox<>();
    txtTglTerimaPenyerahan = new org.jdesktop.swingx.JXDatePicker();
    txtTglJadiPenyerahan = new org.jdesktop.swingx.JXDatePicker();
    txtBanyakCuciPenyerahan = new javax.swing.JTextField();
    jLayeredPane1 = new javax.swing.JLayeredPane();
    txtTambahPakaianPenyerahan = new javax.swing.JTextField();
    btnSimpanPenyerahan = new org.jdesktop.swingx.JXButton();
    btnHapusPenyerahan = new org.jdesktop.swingx.JXButton();
    txtJumlahPakaianPenyerahan = new javax.swing.JTextField();
    btnCetakPenyerahan = new org.jdesktop.swingx.JXButton();
    btnTambahKurangPakaianPenyerahan = new org.jdesktop.swingx.JXButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    tabelPenyerahan = new org.jdesktop.swingx.JXTable();
    tabPengambilan = new javax.swing.JPanel();
    txtNamaPengambilan = new javax.swing.JTextField();
    txtNoNotaPengambilan = new javax.swing.JTextField();
    txtJumlahPengambilan = new javax.swing.JTextField();
    jScrollPane6 = new javax.swing.JScrollPane();
    tabelPengambilan = new javax.swing.JTable();
    cbPewangiPengambilan = new javax.swing.JComboBox<>();
    cbLayananPengambilan = new javax.swing.JComboBox<>();
    txtBanyaknyaCuciPengambilan = new javax.swing.JTextField();
    txtJumlahBayarPengambilan = new javax.swing.JTextField();
    txtBayarPengambilan = new javax.swing.JTextField();
    txtDiskonPengambilan = new javax.swing.JTextField();
    txtKembaliPengambilan = new javax.swing.JTextField();
    jLayeredPane2 = new javax.swing.JLayeredPane();
    txtCariPengambilan = new javax.swing.JTextField();
    btnSimpanPengambilan = new org.jdesktop.swingx.JXButton();
    btnHapusPengambilan = new org.jdesktop.swingx.JXButton();
    btnDetailPakaianPengambilan = new org.jdesktop.swingx.JXButton();
    btnCetakPengambilan = new org.jdesktop.swingx.JXButton();
    btnCariPengambilan = new org.jdesktop.swingx.JXButton();
    txtTglJadiPengambilan = new org.jdesktop.swingx.JXDatePicker();
    txtTglAmbilPengambilan = new org.jdesktop.swingx.JXDatePicker();

    setBorder(null);
    addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
      public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
        formInternalFrameOpened(evt);
      }
    });

    menuLaundry.setBackground(new java.awt.Color(142, 53, 239));
    menuLaundry.setPreferredSize(new java.awt.Dimension(730, 130));
    menuLaundry.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        menuLaundryStateChanged(evt);
      }
    });

    tabPenyerahan.setBackground(new java.awt.Color(142, 53, 239));
    tabPenyerahan.setPreferredSize(new java.awt.Dimension(730, 130));

    txtNamaPenyerahan.setToolTipText("");
    txtNamaPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNamaPenyerahanActionPerformed(evt);
      }
    });

    txtNoNotaPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNoNotaPenyerahanActionPerformed(evt);
      }
    });

    txtJumlahPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtJumlahPenyerahanActionPerformed(evt);
      }
    });

    cbPewangiPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbPewangiPenyerahanActionPerformed(evt);
      }
    });

    cbLayananPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbLayananPenyerahanActionPerformed(evt);
      }
    });

    txtTglTerimaPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtTglTerimaPenyerahanActionPerformed(evt);
      }
    });

    txtTglJadiPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtTglJadiPenyerahanActionPerformed(evt);
      }
    });

    txtBanyakCuciPenyerahan.setEditable(false);

    jLayeredPane1.setBackground(new java.awt.Color(54, 33, 89));
    jLayeredPane1.setOpaque(true);

    txtTambahPakaianPenyerahan.setToolTipText("");

    btnSimpanPenyerahan.setText("Simpan");
    btnSimpanPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSimpanPenyerahanActionPerformed(evt);
      }
    });

    btnHapusPenyerahan.setText("Hapus");
    btnHapusPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnHapusPenyerahanActionPerformed(evt);
      }
    });

    txtJumlahPakaianPenyerahan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txtJumlahPakaianPenyerahan.setToolTipText("");

    btnCetakPenyerahan.setText("Cetak");
    btnCetakPenyerahan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnCetakPenyerahan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCetakPenyerahanActionPerformed(evt);
      }
    });

    btnTambahKurangPakaianPenyerahan.setText("±");

    jLayeredPane1.setLayer(txtTambahPakaianPenyerahan, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(btnSimpanPenyerahan, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(btnHapusPenyerahan, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(txtJumlahPakaianPenyerahan, javax.swing.JLayeredPane.MODAL_LAYER);
    jLayeredPane1.setLayer(btnCetakPenyerahan, javax.swing.JLayeredPane.MODAL_LAYER);
    jLayeredPane1.setLayer(btnTambahKurangPakaianPenyerahan, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
    jLayeredPane1.setLayout(jLayeredPane1Layout);
    jLayeredPane1Layout.setHorizontalGroup(
      jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(txtTambahPakaianPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtJumlahPakaianPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnTambahKurangPakaianPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(65, 65, 65)
        .addComponent(btnSimpanPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnHapusPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnCetakPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jLayeredPane1Layout.setVerticalGroup(
      jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnCetakPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnHapusPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnSimpanPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnTambahKurangPakaianPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtJumlahPakaianPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtTambahPakaianPenyerahan))
        .addContainerGap())
    );

    tabelPenyerahan.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tabelPenyerahan.setEditable(false);
    tabelPenyerahan.setRowHeight(20);
    tabelPenyerahan.setShowGrid(true);
    jScrollPane2.setViewportView(tabelPenyerahan);

    javax.swing.GroupLayout tabPenyerahanLayout = new javax.swing.GroupLayout(tabPenyerahan);
    tabPenyerahan.setLayout(tabPenyerahanLayout);
    tabPenyerahanLayout.setHorizontalGroup(
      tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
      .addGroup(tabPenyerahanLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtNoNotaPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtNamaPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(cbPewangiPenyerahan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cbLayananPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(txtTglTerimaPenyerahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(txtTglJadiPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(txtBanyakCuciPenyerahan)
          .addComponent(txtJumlahPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(45, Short.MAX_VALUE))
      .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    tabPenyerahanLayout.setVerticalGroup(
      tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(tabPenyerahanLayout.createSequentialGroup()
        .addGap(5, 5, 5)
        .addGroup(tabPenyerahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(tabPenyerahanLayout.createSequentialGroup()
            .addComponent(txtNamaPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtNoNotaPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(tabPenyerahanLayout.createSequentialGroup()
            .addComponent(cbPewangiPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbLayananPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(tabPenyerahanLayout.createSequentialGroup()
            .addComponent(txtTglTerimaPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtTglJadiPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(tabPenyerahanLayout.createSequentialGroup()
            .addComponent(txtJumlahPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtBanyakCuciPenyerahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
    );

    menuLaundry.addTab("Penyerahan", tabPenyerahan);

    tabPengambilan.setBackground(new java.awt.Color(142, 53, 239));

    txtNamaPengambilan.setToolTipText("");
    txtNamaPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNamaPengambilanActionPerformed(evt);
      }
    });

    txtNoNotaPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNoNotaPengambilanActionPerformed(evt);
      }
    });

    txtJumlahPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtJumlahPengambilanActionPerformed(evt);
      }
    });

    tabelPengambilan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    tabelPengambilan.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane6.setViewportView(tabelPengambilan);

    cbPewangiPengambilan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    cbLayananPengambilan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    txtBanyaknyaCuciPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtBanyaknyaCuciPengambilanActionPerformed(evt);
      }
    });

    txtJumlahBayarPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtJumlahBayarPengambilanActionPerformed(evt);
      }
    });

    txtBayarPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtBayarPengambilanActionPerformed(evt);
      }
    });

    txtDiskonPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtDiskonPengambilanActionPerformed(evt);
      }
    });

    txtKembaliPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtKembaliPengambilanActionPerformed(evt);
      }
    });

    jLayeredPane2.setBackground(new java.awt.Color(54, 33, 89));
    jLayeredPane2.setOpaque(true);

    txtCariPengambilan.setToolTipText("");

    btnSimpanPengambilan.setText("Simpan");
    btnSimpanPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSimpanPengambilanActionPerformed(evt);
      }
    });

    btnHapusPengambilan.setText("Hapus");
    btnHapusPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnHapusPengambilanActionPerformed(evt);
      }
    });

    btnDetailPakaianPengambilan.setText("Detail");
    btnDetailPakaianPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDetailPakaianPengambilanActionPerformed(evt);
      }
    });

    btnCetakPengambilan.setText("Cetak");
    btnCetakPengambilan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnCetakPengambilan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCetakPengambilanActionPerformed(evt);
      }
    });

    btnCariPengambilan.setText("Cari");

    jLayeredPane2.setLayer(txtCariPengambilan, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(btnSimpanPengambilan, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(btnHapusPengambilan, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(btnDetailPakaianPengambilan, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(btnCetakPengambilan, javax.swing.JLayeredPane.MODAL_LAYER);
    jLayeredPane2.setLayer(btnCariPengambilan, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
    jLayeredPane2.setLayout(jLayeredPane2Layout);
    jLayeredPane2Layout.setHorizontalGroup(
      jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(txtCariPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnCariPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(93, 93, 93)
        .addComponent(btnSimpanPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnHapusPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnDetailPakaianPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnCetakPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(67, Short.MAX_VALUE))
    );
    jLayeredPane2Layout.setVerticalGroup(
      jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnCetakPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnDetailPakaianPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnHapusPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnSimpanPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnCariPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtCariPengambilan))
        .addContainerGap())
    );

    javax.swing.GroupLayout tabPengambilanLayout = new javax.swing.GroupLayout(tabPengambilan);
    tabPengambilan.setLayout(tabPengambilanLayout);
    tabPengambilanLayout.setHorizontalGroup(
      tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane6)
      .addComponent(jLayeredPane2)
      .addGroup(tabPengambilanLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(tabPengambilanLayout.createSequentialGroup()
            .addGroup(tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(tabPengambilanLayout.createSequentialGroup()
                .addComponent(txtNoNotaPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbLayananPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(tabPengambilanLayout.createSequentialGroup()
                .addComponent(txtNamaPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPewangiPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(txtTglAmbilPengambilan, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
              .addComponent(txtTglJadiPengambilan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(8, 8, 8)
            .addGroup(tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtJumlahPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtBanyaknyaCuciPengambilan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(tabPengambilanLayout.createSequentialGroup()
            .addComponent(txtJumlahBayarPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtBayarPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtDiskonPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtKembaliPengambilan, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    tabPengambilanLayout.setVerticalGroup(
      tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(tabPengambilanLayout.createSequentialGroup()
        .addGap(6, 6, 6)
        .addGroup(tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtNamaPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cbPewangiPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtJumlahPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtTglJadiPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(6, 6, 6)
        .addGroup(tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtNoNotaPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cbLayananPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtBanyaknyaCuciPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtTglAmbilPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(tabPengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtJumlahBayarPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtBayarPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtDiskonPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtKembaliPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
    );

    menuLaundry.addTab("Pengambilan", tabPengambilan);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(menuLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(menuLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtNamaPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPenyerahanActionPerformed
    txtNoNotaPenyerahan.requestFocus();
  }//GEN-LAST:event_txtNamaPenyerahanActionPerformed

  private void txtNoNotaPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoNotaPenyerahanActionPerformed
    cbPewangiPenyerahan.requestFocus();
  }//GEN-LAST:event_txtNoNotaPenyerahanActionPerformed

  private void txtJumlahPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahPenyerahanActionPerformed
    controller.simpanPenyerahan(this);
  }//GEN-LAST:event_txtJumlahPenyerahanActionPerformed

  private void txtNamaPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtNamaPengambilanActionPerformed

  private void txtNoNotaPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoNotaPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtNoNotaPengambilanActionPerformed

  private void txtJumlahPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtJumlahPengambilanActionPerformed

   private void menuLaundryStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_menuLaundryStateChanged
     controller.tabItemChangeState(this, evt);
   }//GEN-LAST:event_menuLaundryStateChanged

  private void btnSimpanPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPenyerahanActionPerformed
    controller.simpanPenyerahan(this);
  }//GEN-LAST:event_btnSimpanPenyerahanActionPerformed

  private void btnHapusPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPenyerahanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnHapusPenyerahanActionPerformed

  private void cbLayananPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLayananPenyerahanActionPerformed
    txtTglTerimaPenyerahan.requestFocus();
  }//GEN-LAST:event_cbLayananPenyerahanActionPerformed

  private void txtTglJadiPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglJadiPenyerahanActionPerformed
    txtJumlahPenyerahan.requestFocus();
  }//GEN-LAST:event_txtTglJadiPenyerahanActionPerformed

  private void txtTglTerimaPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglTerimaPenyerahanActionPerformed
    txtTglJadiPenyerahan.requestFocus();
  }//GEN-LAST:event_txtTglTerimaPenyerahanActionPerformed

  private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    txtNamaPenyerahan.requestFocus();
  }//GEN-LAST:event_formInternalFrameOpened

  private void cbPewangiPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPewangiPenyerahanActionPerformed
    cbLayananPenyerahan.requestFocus();
  }//GEN-LAST:event_cbPewangiPenyerahanActionPerformed

  private void btnCetakPenyerahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakPenyerahanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnCetakPenyerahanActionPerformed

  private void txtBanyaknyaCuciPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanyaknyaCuciPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtBanyaknyaCuciPengambilanActionPerformed

  private void txtJumlahBayarPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBayarPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtJumlahBayarPengambilanActionPerformed

  private void txtBayarPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtBayarPengambilanActionPerformed

  private void txtDiskonPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiskonPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtDiskonPengambilanActionPerformed

  private void txtKembaliPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembaliPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtKembaliPengambilanActionPerformed

  private void btnSimpanPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnSimpanPengambilanActionPerformed

  private void btnHapusPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnHapusPengambilanActionPerformed

  private void btnDetailPakaianPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailPakaianPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnDetailPakaianPengambilanActionPerformed

  private void btnCetakPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakPengambilanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnCetakPengambilanActionPerformed

  public JComboBox<String> getCbLayananPenyerahan() {
    return cbLayananPenyerahan;
  }

  public JComboBox<String> getCbPewangiPenyerahan() {
    return cbPewangiPenyerahan;
  }

  public JTextField getTxtJumlahPengambilan() {
    return txtJumlahPengambilan;
  }

  public JTextField getTxtJumlahPenyerahan() {
    return txtJumlahPenyerahan;
  }

  public JTextField getTxtNamaPengambilan() {
    return txtNamaPengambilan;
  }

  public JTextField getTxtNamaPenyerahan() {
    return txtNamaPenyerahan;
  }

  public JTextField getTxtNoNotaPengambilan() {
    return txtNoNotaPengambilan;
  }

  public JTextField getTxtNoNotaPenyerahan() {
    return txtNoNotaPenyerahan;
  }

  public JXDatePicker getTxtTglJadiPengambilan() {
    return txtTglJadiPengambilan;
  }

  public JXDatePicker getTxtTglJadiPenyerahan() {
    return txtTglJadiPenyerahan;
  }

  public JXDatePicker getTxtTglAmbilPengambilan() {
    return txtTglAmbilPengambilan;
  }

  public JXDatePicker getTxtTglTerimaPenyerahan() {
    return txtTglTerimaPenyerahan;
  }

  public JComboBox<String> getCbPewangiPengambilan() {
    return cbPewangiPengambilan;
  }

  public JComboBox<String> getCdLayananPengambilan() {
    return cbLayananPengambilan;
  }

  public JTextField getTxtBanyaknyaCuciPengambilan() {
    return txtBanyaknyaCuciPengambilan;
  }

  public JTextField getTxtTambahPakaianPenyerahan() {
    return txtTambahPakaianPenyerahan;
  }

  public JTextField getTxtJumlahPakaianPenyerahan() {
    return txtJumlahPakaianPenyerahan;
  }

  public JTextField getTxtBanyakCuciPenyerahan() {
    return txtBanyakCuciPenyerahan;
  }

  public JTextField getTxtBayarPengambilan() {
    return txtBayarPengambilan;
  }

  public JTextField getTxtDiskonPengambilan() {
    return txtDiskonPengambilan;
  }

  public JTextField getTxtJumlahBayarPengambilan() {
    return txtJumlahBayarPengambilan;
  }

  public JTextField getTxtKembaliPengambilan() {
    return txtKembaliPengambilan;
  }
  
  public JXTable getTabelPenyerahan() {
    return tabelPenyerahan;
  }
  

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private org.jdesktop.swingx.JXButton btnCariPengambilan;
  private org.jdesktop.swingx.JXButton btnCetakPengambilan;
  private org.jdesktop.swingx.JXButton btnCetakPenyerahan;
  private org.jdesktop.swingx.JXButton btnDetailPakaianPengambilan;
  private org.jdesktop.swingx.JXButton btnHapusPengambilan;
  private org.jdesktop.swingx.JXButton btnHapusPenyerahan;
  private org.jdesktop.swingx.JXButton btnSimpanPengambilan;
  private org.jdesktop.swingx.JXButton btnSimpanPenyerahan;
  private org.jdesktop.swingx.JXButton btnTambahKurangPakaianPenyerahan;
  private javax.swing.JComboBox<String> cbLayananPengambilan;
  private javax.swing.JComboBox<String> cbLayananPenyerahan;
  private javax.swing.JComboBox<String> cbPewangiPengambilan;
  private javax.swing.JComboBox<String> cbPewangiPenyerahan;
  private javax.swing.JLayeredPane jLayeredPane1;
  private javax.swing.JLayeredPane jLayeredPane2;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane6;
  private javax.swing.JTabbedPane menuLaundry;
  private javax.swing.JPanel tabPengambilan;
  private javax.swing.JPanel tabPenyerahan;
  private javax.swing.JTable tabelPengambilan;
  private org.jdesktop.swingx.JXTable tabelPenyerahan;
  private javax.swing.JTextField txtBanyakCuciPenyerahan;
  private javax.swing.JTextField txtBanyaknyaCuciPengambilan;
  private javax.swing.JTextField txtBayarPengambilan;
  private javax.swing.JTextField txtCariPengambilan;
  private javax.swing.JTextField txtDiskonPengambilan;
  private javax.swing.JTextField txtJumlahBayarPengambilan;
  private javax.swing.JTextField txtJumlahPakaianPenyerahan;
  private javax.swing.JTextField txtJumlahPengambilan;
  private javax.swing.JTextField txtJumlahPenyerahan;
  private javax.swing.JTextField txtKembaliPengambilan;
  private javax.swing.JTextField txtNamaPengambilan;
  private javax.swing.JTextField txtNamaPenyerahan;
  private javax.swing.JTextField txtNoNotaPengambilan;
  private javax.swing.JTextField txtNoNotaPenyerahan;
  private javax.swing.JTextField txtTambahPakaianPenyerahan;
  private org.jdesktop.swingx.JXDatePicker txtTglAmbilPengambilan;
  private org.jdesktop.swingx.JXDatePicker txtTglJadiPengambilan;
  private org.jdesktop.swingx.JXDatePicker txtTglJadiPenyerahan;
  private org.jdesktop.swingx.JXDatePicker txtTglTerimaPenyerahan;
  // End of variables declaration//GEN-END:variables
}
